type: '*routingprocessor.Config'
doc: |
  Config defines configuration for the Routing processor.
fields:
- name: default_exporters
  type: '[]string'
  kind: slice
  doc: |
    DefaultExporters contains the list of exporters to use when a more specific record can't be found in the routing table.
    Optional.
- name: attribute_source
  type: routingprocessor.AttributeSource
  kind: string
  default: context
  doc: |
    AttributeSource defines where the attribute defined in `from_attribute` is searched for.
    The allowed values are:
    - "context" - the attribute must exist in the incoming context
    - "resource" - the attribute must exist in resource attributes
    The default value is "context".
    Optional.
- name: from_attribute
  kind: string
  default: ""
  doc: |
    FromAttribute contains the attribute name to look up the route value. This attribute should be part of the context propagated
    down from the previous receivers and/or processors. If all the receivers and processors are propagating the entire context correctly,
    this could be the HTTP/gRPC header from the original request/RPC. Typically, aggregation processors (batch, groupbytrace)
    will create a new context, so, those should be avoided when using this processor.Although the HTTP spec allows headers to be repeated,
    this processor will only use the first value.
    Required.
- name: drop_resource_routing_attribute
  kind: bool
  default: false
  doc: |
    DropRoutingResourceAttribute controls whether to remove the resource attribute used for routing.
    This is only relevant if AttributeSource is set to resource.
    Optional.
- name: table
  type: '[]routingprocessor.RoutingTableItem'
  kind: slice
  doc: |
    Table contains the routing table for this processor.
    Required.
  fields:
  - name: value
    kind: string
    default: ""
    doc: |
      Value represents a possible value for the field specified under FromAttribute.
      Required when 'Expression' isn't provided.
  - name: expression
    kind: string
    default: ""
    doc: |
      Expression is a OTTL expression on which signals routing is based.
      Required when 'Value' isn't provided.
  - name: exporters
    type: '[]string'
    kind: slice
    doc: |
      Exporters contains the list of exporters to use when the value from the FromAttribute field matches this table item.
      When no exporters are specified, the ones specified under DefaultExporters are used, if any.
      The routing processor will fail upon the first failure from these exporters.
      Optional.
