type: '*googlemanagedprometheusexporter.Config'
doc: |
  Config defines configuration for Google Cloud Managed Service for Prometheus exporter.
fields:
- name: project
  kind: string
  default: ""
- name: user_agent
  kind: string
  default: ""
- name: getclientoptions
  type: func() []option.ClientOption
  kind: func
  doc: |
    GetClientOptions returns additional options to be passed
    to the underlying Google Cloud API client.
    Must be set programmatically (no support via declarative config).
    Optional.
- name: endpoint
  kind: string
  default: ""
- name: use_insecure
  kind: bool
  default: false
  doc: |
    Only has effect if Endpoint is not ""
- name: grpc_pool_size
  kind: int
  doc: |
    GRPCPoolSize sets the size of the connection pool in the GCP client
- name: timeout
  type: time.Duration
  kind: int64
  default: 12s
  doc: |
    Timeout is the timeout for every attempt to send data to the backend.
- name: sending_queue
  type: exporterhelper.QueueSettings
  kind: struct
  doc: |
    QueueSettings defines configuration for queueing batches before sending to the consumerSender.
  fields:
  - name: enabled
    kind: bool
    default: true
    doc: |
      Enabled indicates whether to not enqueue batches before sending to the consumerSender.
  - name: num_consumers
    kind: int
    default: 10
    doc: |
      NumConsumers is the number of consumers from the queue.
  - name: queue_size
    kind: int
    default: 5000
    doc: |
      QueueSize is the maximum number of batches allowed in queue at a given time.
  - name: storage
    type: '*config.ComponentID'
    kind: ptr
    doc: |
      StorageID if not empty, enables the persistent storage and uses the component specified
      as a storage extension for the persistent queue
- name: retry_on_failure
  type: exporterhelper.RetrySettings
  kind: struct
  doc: |
    RetrySettings defines configuration for retrying batches in case of export failure.
    The current supported strategy is exponential backoff.
  fields:
  - name: enabled
    kind: bool
    default: true
    doc: |
      Enabled indicates whether to not retry sending batches in case of export failure.
  - name: initial_interval
    type: time.Duration
    kind: int64
    default: 5s
    doc: |
      InitialInterval the time to wait after the first failure before retrying.
  - name: max_interval
    type: time.Duration
    kind: int64
    default: 30s
    doc: |
      MaxInterval is the upper bound on backoff interval. Once this value is reached the delay between
      consecutive retries will always be `MaxInterval`.
  - name: max_elapsed_time
    type: time.Duration
    kind: int64
    default: 5m0s
    doc: |
      MaxElapsedTime is the maximum amount of time (including retries) spent trying to send a request/batch.
      Once this value is reached, the data is discarded.
